# Generated by Django 6.0.2 on 2026-03-17 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('vds', '0008_mtprotokey_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_payment_charge_id',
            field=models.CharField(blank=True, verbose_name='UUID платежа на ЮKassa'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassa_payment', to='vds.mtprotokey', verbose_name='ключ'),
        ),
    ]
