# Generated by Django 6.0.2 on 2026-02-26 10:16

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_systemuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='systemuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
