# Generated by Django 6.0.2 on 2026-02-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_systemuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='first_month_free_used',
            field=models.BooleanField(default=False, verbose_name='бесплатный месяц использован'),
        ),
    ]
