# Generated by Django 6.0.2 on 2026-03-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_systemuser_first_month_free_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='telegram_username',
            field=models.CharField(blank=True, verbose_name='имя пользователя в Telegram'),
        ),
    ]
