# Generated by Django 6.0.2 on 2026-03-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_systemuser_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='invited_from_username',
            field=models.CharField(blank=True, verbose_name='TG-ID от кого пришел пользователь'),
        ),
    ]
