# Generated by Django 6.0.2 on 2026-03-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_systemuser_invited_from_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='referral_activated',
            field=models.BooleanField(default=False, verbose_name='реферал активирован'),
        ),
    ]
