# Generated by Django 6.0.2 on 2026-03-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_systemuser_referral_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='referral_link_activated_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='количество активированных реф. ссылок'),
        ),
    ]
