# Generated by Django 6.0.2 on 2026-03-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_systemuser_referral_link_activated_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='invited_from_username',
            field=models.CharField(blank=True, null=True, verbose_name='TG-ID от кого пришел пользователь'),
        ),
    ]
