# Generated by Django 6.0.2 on 2026-03-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_systemuser_invited_from_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='notified_update_link',
            field=models.BooleanField(default=False, verbose_name='уведомлен о возможности перевыпуска'),
        ),
    ]
