services:
  django:
    build: .
    image: my-django:latest
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: django
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - static_volume:/app/static
      - ./data:/app/data
    env_file:
      - .env
    expose:
      - 8000
    networks:
      - backend

  nginx:
    build: ./nginx
    image: my-nginx:latest
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: nginx
    volumes:
      - static_volume:/static:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot:ro
    expose:
      - "8443"
      - "80"
    networks:
      - backend
    depends_on:
      - django

  haproxy:
    image: haproxy:lts-alpine
    container_name: haproxy
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
    expose:
      - "8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - nginx

volumes:
  static_volume:

networks:
  backend:
    driver: bridge