# Generated by Django 6.0.2 on 2026-02-23 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VDSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('name', models.CharField(unique=True, verbose_name='название сервера')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='порядковый номер')),
                ('ip_address', models.CharField(unique=True, verbose_name='IP-адрес')),
                ('port', models.SmallIntegerField(default=8000, verbose_name='порт')),
            ],
            options={
                'verbose_name': 'VDS сервер',
                'verbose_name_plural': 'VDS серверы',
            },
        ),
        migrations.CreateModel(
            name='MTPRotoKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('token', models.CharField(unique=True, verbose_name='токен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('vds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='vds.vdsinstance', verbose_name='VDS сервер')),
            ],
            options={
                'verbose_name': 'MTPRoto ключ',
                'verbose_name_plural': 'MTPRoto ключи',
            },
        ),
    ]
