# Generated by Django 6.0.2 on 2026-02-23 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribute', '0001_initial'),
        ('vds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtprotokey',
            name='payment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='tribute.tributedigitalpayment', verbose_name='оплата на Tribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtprotokey',
            name='tls_domain',
            field=models.CharField(default='', verbose_name='домен ключа в telemt'),
            preserve_default=False,
        ),
    ]
