# Generated by Django 6.0.2 on 2026-02-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0002_mtprotokey_payment_mtprotokey_tls_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtprotokey',
            name='was_deleted',
            field=models.BooleanField(default=False, verbose_name='удален'),
        ),
    ]
