# Generated by Django 6.0.2 on 2026-02-28 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribute', '0002_tributedigitalpayment_is_success'),
        ('vds', '0003_mtprotokey_was_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtprotokey',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='tribute.tributedigitalpayment', verbose_name='оплата на Tribute'),
        ),
    ]
