# Generated by Django 6.0.2 on 2026-02-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0004_alter_mtprotokey_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdsinstance',
            name='internal_ip_address',
            field=models.CharField(blank=True, verbose_name='внутренний IP-адрес'),
        ),
    ]
