# Generated by Django 6.0.2 on 2026-03-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0005_vdsinstance_internal_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtprotokey',
            name='node_number',
            field=models.CharField(blank=True, verbose_name='номер ноды'),
        ),
    ]
