# Generated by Django 6.0.2 on 2026-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0006_mtprotokey_node_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtprotokey',
            name='user_notified',
            field=models.BooleanField(default=False, verbose_name='уведомлен об истечении'),
        ),
    ]
