# Generated by Django 6.0.2 on 2026-03-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0007_mtprotokey_user_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtprotokey',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='истекает'),
        ),
    ]
