# Generated by Django 6.0.2 on 2026-03-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vds', '0008_mtprotokey_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtprotokey',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последнее обновление'),
        ),
    ]
