# Generated by Django 6.0.2 on 2026-02-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TributeDigitalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('name', models.CharField(verbose_name='название события')),
                ('product_id', models.IntegerField(verbose_name='ID товара')),
                ('product_name', models.CharField(verbose_name='название товара')),
                ('amount', models.FloatField(verbose_name='стоимость')),
                ('currency', models.CharField(verbose_name='валюта')),
                ('telegram_user_id', models.CharField(verbose_name='ID пользователя в Telegram')),
                ('purchase_created_at', models.DateTimeField(verbose_name='дата оплаты на Tribute')),
            ],
            options={
                'verbose_name': 'платеж на Tribute',
                'verbose_name_plural': 'платежи на Tribute',
            },
        ),
    ]
