# Generated by Django 6.0.2 on 2026-02-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tributedigitalpayment',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='ссылка отправлена пользователю'),
        ),
    ]
